// Golden-fixture tests for graphToPrompt: full serialized-workflow fixtures
// (including the cosmetic noise fields `convertToLiteGraph()` actually emits
// — pos/size/title/color/bgcolor/properties.comfynext_preview/groups/extra)
// run end-to-end against an expected API-prompt JSON that was HAND-DERIVED
// from the documented semantics in graphToPrompt.ts / widgetOrder.ts /
// flattenSubgraphs.ts — never generated by running the builder and pasting
// its output. See frontend/tests/unit/__fixtures__/golden/ for the raw
// fixtures; this file's report documents the derivation of each expected
// prompt.
import { describe, it, expect } from 'vitest'
import { graphToPrompt } from '~/lib/graph/graphToPrompt'
import type { LiteGraphWorkflow } from '~/composables/useVueNodes'

import txt2imgWorkflow from './__fixtures__/golden/txt2img-seed-control.json'
import txt2imgExpected from './__fixtures__/golden/txt2img-seed-control.prompt.json'
import muteBypassWorkflow from './__fixtures__/golden/mute-bypass-mix.json'
import muteBypassExpected from './__fixtures__/golden/mute-bypass-mix.prompt.json'
import subgraphWorkflow from './__fixtures__/golden/subgraph-converted-widget-mix.json'
import subgraphExpected from './__fixtures__/golden/subgraph-converted-widget-mix.prompt.json'

// Shared object_info covering every class_type referenced across the three
// golden fixtures. Shapes mirror ComfyUI's real /object_info closely enough
// to exercise widgetSlots() (see graph-to-prompt.unit.spec.ts /
// flatten-subgraphs.unit.spec.ts for the same idiom).
const OBJECT_INFO = {
  CheckpointLoaderSimple: {
    input: {
      required: {
        ckpt_name: [['model_a.safetensors', 'model_b.safetensors'], {}],
      },
    },
  },
  KSampler: {
    input: {
      required: {
        model: ['MODEL', {}],
        positive: ['CONDITIONING', {}],
        negative: ['CONDITIONING', {}],
        latent_image: ['LATENT', {}],
        seed: ['INT', { control_after_generate: true }],
        steps: ['INT', {}],
        cfg: ['FLOAT', {}],
        sampler_name: [['euler', 'dpmpp_2m'], {}],
      },
    },
  },
  VAEDecode: {
    input: {
      required: {
        samples: ['LATENT', {}],
        vae: ['VAE', {}],
      },
    },
  },
  SaveImage: {
    input: {
      required: {
        images: ['IMAGE', {}],
        filename_prefix: ['STRING', {}],
      },
    },
  },
  LoadImageNode: {
    input: {
      required: {
        image: [['photo.png'], {}],
      },
    },
  },
  EnhanceNode: {
    input: {
      required: {
        image: ['IMAGE', {}],
        strength: ['FLOAT', {}],
      },
    },
  },
  FloatInputNode: {
    input: {
      required: {
        value: ['FLOAT', {}],
      },
    },
  },
  ModelConsumerNode: {
    input: {
      required: {
        model: ['MODEL', {}],
      },
    },
  },
  IntInputNode: {
    input: {
      required: {
        value: ['INT', {}],
      },
    },
  },
  MultiplyNode: {
    input: {
      required: {
        value: ['INT', {}],
        factor: ['INT', {}],
      },
    },
  },
  IntSinkNode: {
    input: {
      required: {
        value: ['INT', {}],
      },
    },
  },
  // Interior node inside the SeedGen subgraph definition — `seed` carries
  // `control_after_generate`, so widgetSlots() inserts a synthetic
  // `seed__control` slot right after it (positions: 0=seed,
  // 1=seed__control, 2=steps), matching the real blueprints' KSampler shape.
  KSamplerIsh: {
    input: {
      required: {
        seed: ['INT', { control_after_generate: true }],
        steps: ['INT', {}],
      },
    },
  },
}

describe('graphToPrompt golden fixtures', () => {
  it('txt2img-seed-control: builds the exact hand-derived prompt', () => {
    const prompt = graphToPrompt(txt2imgWorkflow as unknown as LiteGraphWorkflow, OBJECT_INFO)
    expect(prompt).toEqual(txt2imgExpected)
  })

  it('mute-bypass-mix: builds the exact hand-derived prompt', () => {
    const prompt = graphToPrompt(muteBypassWorkflow as unknown as LiteGraphWorkflow, OBJECT_INFO)
    expect(prompt).toEqual(muteBypassExpected)
  })

  it('subgraph-converted-widget-mix: builds the exact hand-derived prompt', () => {
    const prompt = graphToPrompt(subgraphWorkflow as unknown as LiteGraphWorkflow, OBJECT_INFO)
    expect(prompt).toEqual(subgraphExpected)
  })

  describe('determinism', () => {
    const fixtures: [string, LiteGraphWorkflow][] = [
      ['txt2img-seed-control', txt2imgWorkflow as unknown as LiteGraphWorkflow],
      ['mute-bypass-mix', muteBypassWorkflow as unknown as LiteGraphWorkflow],
      ['subgraph-converted-widget-mix', subgraphWorkflow as unknown as LiteGraphWorkflow],
    ]

    for (const [name, workflow] of fixtures) {
      it(`${name}: two calls on the same input produce JSON.stringify-identical output`, () => {
        const first = graphToPrompt(workflow, OBJECT_INFO)
        const second = graphToPrompt(workflow, OBJECT_INFO)
        expect(JSON.stringify(first)).toBe(JSON.stringify(second))
      })
    }
  })
})
