
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const UiAvatar: typeof import("../app/components/ui/avatar/Avatar.vue")['default']
export const UiAvatarFallback: typeof import("../app/components/ui/avatar/AvatarFallback.vue")['default']
export const UiAvatarImage: typeof import("../app/components/ui/avatar/AvatarImage.vue")['default']
export const UiBadge: typeof import("../app/components/ui/badge/Badge.vue")['default']
export const UiButton: typeof import("../app/components/ui/button/Button.vue")['default']
export const UiInput: typeof import("../app/components/ui/input/Input.vue")['default']
export const UiSelect: typeof import("../app/components/ui/select/Select.vue")['default']
export const UiSelectContent: typeof import("../app/components/ui/select/SelectContent.vue")['default']
export const UiSelectGroup: typeof import("../app/components/ui/select/SelectGroup.vue")['default']
export const UiSelectItem: typeof import("../app/components/ui/select/SelectItem.vue")['default']
export const UiSelectLabel: typeof import("../app/components/ui/select/SelectLabel.vue")['default']
export const UiSelectSeparator: typeof import("../app/components/ui/select/SelectSeparator.vue")['default']
export const UiSelectTrigger: typeof import("../app/components/ui/select/SelectTrigger.vue")['default']
export const UiSelectValue: typeof import("../app/components/ui/select/SelectValue.vue")['default']
export const UiSeparator: typeof import("../app/components/ui/separator/Separator.vue")['default']
export const UiSheet: typeof import("../app/components/ui/sheet/Sheet.vue")['default']
export const UiSheetClose: typeof import("../app/components/ui/sheet/SheetClose.vue")['default']
export const UiSheetContent: typeof import("../app/components/ui/sheet/SheetContent.vue")['default']
export const UiSheetDescription: typeof import("../app/components/ui/sheet/SheetDescription.vue")['default']
export const UiSheetFooter: typeof import("../app/components/ui/sheet/SheetFooter.vue")['default']
export const UiSheetHeader: typeof import("../app/components/ui/sheet/SheetHeader.vue")['default']
export const UiSheetOverlay: typeof import("../app/components/ui/sheet/SheetOverlay.vue")['default']
export const UiSheetTitle: typeof import("../app/components/ui/sheet/SheetTitle.vue")['default']
export const UiSheetTrigger: typeof import("../app/components/ui/sheet/SheetTrigger.vue")['default']
export const UiSidebar: typeof import("../app/components/ui/sidebar/Sidebar.vue")['default']
export const UiSidebarContent: typeof import("../app/components/ui/sidebar/SidebarContent.vue")['default']
export const UiSidebarFooter: typeof import("../app/components/ui/sidebar/SidebarFooter.vue")['default']
export const UiSidebarGroup: typeof import("../app/components/ui/sidebar/SidebarGroup.vue")['default']
export const UiSidebarGroupAction: typeof import("../app/components/ui/sidebar/SidebarGroupAction.vue")['default']
export const UiSidebarGroupContent: typeof import("../app/components/ui/sidebar/SidebarGroupContent.vue")['default']
export const UiSidebarGroupLabel: typeof import("../app/components/ui/sidebar/SidebarGroupLabel.vue")['default']
export const UiSidebarHeader: typeof import("../app/components/ui/sidebar/SidebarHeader.vue")['default']
export const UiSidebarInput: typeof import("../app/components/ui/sidebar/SidebarInput.vue")['default']
export const UiSidebarInset: typeof import("../app/components/ui/sidebar/SidebarInset.vue")['default']
export const UiSidebarMenu: typeof import("../app/components/ui/sidebar/SidebarMenu.vue")['default']
export const UiSidebarMenuAction: typeof import("../app/components/ui/sidebar/SidebarMenuAction.vue")['default']
export const UiSidebarMenuBadge: typeof import("../app/components/ui/sidebar/SidebarMenuBadge.vue")['default']
export const UiSidebarMenuButton: typeof import("../app/components/ui/sidebar/SidebarMenuButton.vue")['default']
export const UiSidebarMenuButtonChild: typeof import("../app/components/ui/sidebar/SidebarMenuButtonChild.vue")['default']
export const UiSidebarMenuItem: typeof import("../app/components/ui/sidebar/SidebarMenuItem.vue")['default']
export const UiSidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/SidebarMenuSkeleton.vue")['default']
export const UiSidebarMenuSub: typeof import("../app/components/ui/sidebar/SidebarMenuSub.vue")['default']
export const UiSidebarMenuSubButton: typeof import("../app/components/ui/sidebar/SidebarMenuSubButton.vue")['default']
export const UiSidebarMenuSubItem: typeof import("../app/components/ui/sidebar/SidebarMenuSubItem.vue")['default']
export const UiSidebarProvider: typeof import("../app/components/ui/sidebar/SidebarProvider.vue")['default']
export const UiSidebarRail: typeof import("../app/components/ui/sidebar/SidebarRail.vue")['default']
export const UiSidebarSeparator: typeof import("../app/components/ui/sidebar/SidebarSeparator.vue")['default']
export const UiSidebarTrigger: typeof import("../app/components/ui/sidebar/SidebarTrigger.vue")['default']
export const UiSonner: typeof import("../app/components/ui/sonner/Sonner.vue")['default']
export const UiTextarea: typeof import("../app/components/ui/textarea/Textarea.vue")['default']
export const UiTooltip: typeof import("../app/components/ui/tooltip/Tooltip.vue")['default']
export const UiTooltipContent: typeof import("../app/components/ui/tooltip/TooltipContent.vue")['default']
export const UiTooltipProvider: typeof import("../app/components/ui/tooltip/TooltipProvider.vue")['default']
export const UiTooltipTrigger: typeof import("../app/components/ui/tooltip/TooltipTrigger.vue")['default']
export const AppSidebar: typeof import("../app/components/AppSidebar.vue")['default']
export const AssetBundleOverlay: typeof import("../app/components/AssetBundleOverlay.vue")['default']
export const AssetDetailOverlay: typeof import("../app/components/AssetDetailOverlay.vue")['default']
export const AssetsHistory: typeof import("../app/components/AssetsHistory.vue")['default']
export const ExplainOverlay: typeof import("../app/components/ExplainOverlay.vue")['default']
export const ExplainPanel: typeof import("../app/components/ExplainPanel.vue")['default']
export const LoraTrainerSurface: typeof import("../app/components/LoraTrainerSurface.vue")['default']
export const NodeSearchDialog: typeof import("../app/components/NodeSearchDialog.vue")['default']
export const SettingsModal: typeof import("../app/components/SettingsModal.vue")['default']
export const UserPopup: typeof import("../app/components/UserPopup.vue")['default']
export const AppsAppFileSlot: typeof import("../app/components/apps/AppFileSlot.vue")['default']
export const AppsAutoSubtitleApp: typeof import("../app/components/apps/AutoSubtitleApp.vue")['default']
export const AppsFaceSwapApp: typeof import("../app/components/apps/FaceSwapApp.vue")['default']
export const AppsKaraokeMakerApp: typeof import("../app/components/apps/KaraokeMakerApp.vue")['default']
export const TemplatesEditorCanvas: typeof import("../app/components/templates/EditorCanvas.vue")['default']
export const TemplatesEditorShell: typeof import("../app/components/templates/EditorShell.vue")['default']
export const TemplatesLayersPanel: typeof import("../app/components/templates/LayersPanel.vue")['default']
export const TemplatesPropertyPanel: typeof import("../app/components/templates/PropertyPanel.vue")['default']
export const VueCanvasAnimatedDotGrid: typeof import("../app/components/vue-canvas/AnimatedDotGrid.vue")['default']
export const VueCanvasAsciiPanel: typeof import("../app/components/vue-canvas/AsciiPanel.vue")['default']
export const VueCanvasComfyEdge: typeof import("../app/components/vue-canvas/ComfyEdge.vue")['default']
export const VueCanvasComfyGateNode: typeof import("../app/components/vue-canvas/ComfyGateNode.vue")['default']
export const VueCanvasComfyNode: typeof import("../app/components/vue-canvas/ComfyNode.vue")['default']
export const VueCanvasComfyNodePort: typeof import("../app/components/vue-canvas/ComfyNodePort.vue")['default']
export const VueCanvasComfyNodeWidget: typeof import("../app/components/vue-canvas/ComfyNodeWidget.vue")['default']
export const VueCanvasComfyNoteNode: typeof import("../app/components/vue-canvas/ComfyNoteNode.vue")['default']
export const VueCanvasCompositorModal: typeof import("../app/components/vue-canvas/CompositorModal.vue")['default']
export const VueCanvasCrossfadeModal: typeof import("../app/components/vue-canvas/CrossfadeModal.vue")['default']
export const VueCanvasGeneratorsPanel: typeof import("../app/components/vue-canvas/GeneratorsPanel.vue")['default']
export const VueCanvasLoRALibraryPanel: typeof import("../app/components/vue-canvas/LoRALibraryPanel.vue")['default']
export const VueCanvasNodesCategoryFolder: typeof import("../app/components/vue-canvas/NodesCategoryFolder.vue")['default']
export const VueCanvasNodesSidebar: typeof import("../app/components/vue-canvas/NodesSidebar.vue")['default']
export const VueCanvasSmartLayoutEditorModal: typeof import("../app/components/vue-canvas/SmartLayoutEditorModal.vue")['default']
export const VueCanvasSubgraphBreadcrumb: typeof import("../app/components/vue-canvas/SubgraphBreadcrumb.vue")['default']
export const VueCanvasSubgraphIONode: typeof import("../app/components/vue-canvas/SubgraphIONode.vue")['default']
export const VueCanvasTimelineModal: typeof import("../app/components/vue-canvas/TimelineModal.vue")['default']
export const VueCanvasTimelineNodePreview: typeof import("../app/components/vue-canvas/TimelineNodePreview.vue")['default']
export const VueCanvasToolboxPanel: typeof import("../app/components/vue-canvas/ToolboxPanel.vue")['default']
export const VueCanvasVueNodeCanvas: typeof import("../app/components/vue-canvas/VueNodeCanvas.vue")['default']
export const VueCanvasWorkflowOverview: typeof import("../app/components/vue-canvas/WorkflowOverview.vue")['default']
export const VueCanvasWidgetsWidgetCombo: typeof import("../app/components/vue-canvas/widgets/WidgetCombo.vue")['default']
export const VueCanvasWidgetsWidgetGradientSlider: typeof import("../app/components/vue-canvas/widgets/WidgetGradientSlider.vue")['default']
export const VueCanvasWidgetsWidgetNumber: typeof import("../app/components/vue-canvas/widgets/WidgetNumber.vue")['default']
export const VueCanvasWidgetsWidgetSeed: typeof import("../app/components/vue-canvas/widgets/WidgetSeed.vue")['default']
export const VueCanvasWidgetsWidgetText: typeof import("../app/components/vue-canvas/widgets/WidgetText.vue")['default']
export const VueCanvasWidgetsWidgetToggle: typeof import("../app/components/vue-canvas/widgets/WidgetToggle.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUiAvatar: LazyComponent<typeof import("../app/components/ui/avatar/Avatar.vue")['default']>
export const LazyUiAvatarFallback: LazyComponent<typeof import("../app/components/ui/avatar/AvatarFallback.vue")['default']>
export const LazyUiAvatarImage: LazyComponent<typeof import("../app/components/ui/avatar/AvatarImage.vue")['default']>
export const LazyUiBadge: LazyComponent<typeof import("../app/components/ui/badge/Badge.vue")['default']>
export const LazyUiButton: LazyComponent<typeof import("../app/components/ui/button/Button.vue")['default']>
export const LazyUiInput: LazyComponent<typeof import("../app/components/ui/input/Input.vue")['default']>
export const LazyUiSelect: LazyComponent<typeof import("../app/components/ui/select/Select.vue")['default']>
export const LazyUiSelectContent: LazyComponent<typeof import("../app/components/ui/select/SelectContent.vue")['default']>
export const LazyUiSelectGroup: LazyComponent<typeof import("../app/components/ui/select/SelectGroup.vue")['default']>
export const LazyUiSelectItem: LazyComponent<typeof import("../app/components/ui/select/SelectItem.vue")['default']>
export const LazyUiSelectLabel: LazyComponent<typeof import("../app/components/ui/select/SelectLabel.vue")['default']>
export const LazyUiSelectSeparator: LazyComponent<typeof import("../app/components/ui/select/SelectSeparator.vue")['default']>
export const LazyUiSelectTrigger: LazyComponent<typeof import("../app/components/ui/select/SelectTrigger.vue")['default']>
export const LazyUiSelectValue: LazyComponent<typeof import("../app/components/ui/select/SelectValue.vue")['default']>
export const LazyUiSeparator: LazyComponent<typeof import("../app/components/ui/separator/Separator.vue")['default']>
export const LazyUiSheet: LazyComponent<typeof import("../app/components/ui/sheet/Sheet.vue")['default']>
export const LazyUiSheetClose: LazyComponent<typeof import("../app/components/ui/sheet/SheetClose.vue")['default']>
export const LazyUiSheetContent: LazyComponent<typeof import("../app/components/ui/sheet/SheetContent.vue")['default']>
export const LazyUiSheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/SheetDescription.vue")['default']>
export const LazyUiSheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/SheetFooter.vue")['default']>
export const LazyUiSheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/SheetHeader.vue")['default']>
export const LazyUiSheetOverlay: LazyComponent<typeof import("../app/components/ui/sheet/SheetOverlay.vue")['default']>
export const LazyUiSheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/SheetTitle.vue")['default']>
export const LazyUiSheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/SheetTrigger.vue")['default']>
export const LazyUiSidebar: LazyComponent<typeof import("../app/components/ui/sidebar/Sidebar.vue")['default']>
export const LazyUiSidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarContent.vue")['default']>
export const LazyUiSidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarFooter.vue")['default']>
export const LazyUiSidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarGroup.vue")['default']>
export const LazyUiSidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarGroupAction.vue")['default']>
export const LazyUiSidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarGroupContent.vue")['default']>
export const LazyUiSidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarGroupLabel.vue")['default']>
export const LazyUiSidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarHeader.vue")['default']>
export const LazyUiSidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarInput.vue")['default']>
export const LazyUiSidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarInset.vue")['default']>
export const LazyUiSidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenu.vue")['default']>
export const LazyUiSidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuAction.vue")['default']>
export const LazyUiSidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuBadge.vue")['default']>
export const LazyUiSidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuButton.vue")['default']>
export const LazyUiSidebarMenuButtonChild: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuButtonChild.vue")['default']>
export const LazyUiSidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuItem.vue")['default']>
export const LazyUiSidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuSkeleton.vue")['default']>
export const LazyUiSidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuSub.vue")['default']>
export const LazyUiSidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuSubButton.vue")['default']>
export const LazyUiSidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarMenuSubItem.vue")['default']>
export const LazyUiSidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarProvider.vue")['default']>
export const LazyUiSidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarRail.vue")['default']>
export const LazyUiSidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarSeparator.vue")['default']>
export const LazyUiSidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/SidebarTrigger.vue")['default']>
export const LazyUiSonner: LazyComponent<typeof import("../app/components/ui/sonner/Sonner.vue")['default']>
export const LazyUiTextarea: LazyComponent<typeof import("../app/components/ui/textarea/Textarea.vue")['default']>
export const LazyUiTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/Tooltip.vue")['default']>
export const LazyUiTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/TooltipContent.vue")['default']>
export const LazyUiTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/TooltipProvider.vue")['default']>
export const LazyUiTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/TooltipTrigger.vue")['default']>
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/AppSidebar.vue")['default']>
export const LazyAssetBundleOverlay: LazyComponent<typeof import("../app/components/AssetBundleOverlay.vue")['default']>
export const LazyAssetDetailOverlay: LazyComponent<typeof import("../app/components/AssetDetailOverlay.vue")['default']>
export const LazyAssetsHistory: LazyComponent<typeof import("../app/components/AssetsHistory.vue")['default']>
export const LazyExplainOverlay: LazyComponent<typeof import("../app/components/ExplainOverlay.vue")['default']>
export const LazyExplainPanel: LazyComponent<typeof import("../app/components/ExplainPanel.vue")['default']>
export const LazyLoraTrainerSurface: LazyComponent<typeof import("../app/components/LoraTrainerSurface.vue")['default']>
export const LazyNodeSearchDialog: LazyComponent<typeof import("../app/components/NodeSearchDialog.vue")['default']>
export const LazySettingsModal: LazyComponent<typeof import("../app/components/SettingsModal.vue")['default']>
export const LazyUserPopup: LazyComponent<typeof import("../app/components/UserPopup.vue")['default']>
export const LazyAppsAppFileSlot: LazyComponent<typeof import("../app/components/apps/AppFileSlot.vue")['default']>
export const LazyAppsAutoSubtitleApp: LazyComponent<typeof import("../app/components/apps/AutoSubtitleApp.vue")['default']>
export const LazyAppsFaceSwapApp: LazyComponent<typeof import("../app/components/apps/FaceSwapApp.vue")['default']>
export const LazyAppsKaraokeMakerApp: LazyComponent<typeof import("../app/components/apps/KaraokeMakerApp.vue")['default']>
export const LazyTemplatesEditorCanvas: LazyComponent<typeof import("../app/components/templates/EditorCanvas.vue")['default']>
export const LazyTemplatesEditorShell: LazyComponent<typeof import("../app/components/templates/EditorShell.vue")['default']>
export const LazyTemplatesLayersPanel: LazyComponent<typeof import("../app/components/templates/LayersPanel.vue")['default']>
export const LazyTemplatesPropertyPanel: LazyComponent<typeof import("../app/components/templates/PropertyPanel.vue")['default']>
export const LazyVueCanvasAnimatedDotGrid: LazyComponent<typeof import("../app/components/vue-canvas/AnimatedDotGrid.vue")['default']>
export const LazyVueCanvasAsciiPanel: LazyComponent<typeof import("../app/components/vue-canvas/AsciiPanel.vue")['default']>
export const LazyVueCanvasComfyEdge: LazyComponent<typeof import("../app/components/vue-canvas/ComfyEdge.vue")['default']>
export const LazyVueCanvasComfyGateNode: LazyComponent<typeof import("../app/components/vue-canvas/ComfyGateNode.vue")['default']>
export const LazyVueCanvasComfyNode: LazyComponent<typeof import("../app/components/vue-canvas/ComfyNode.vue")['default']>
export const LazyVueCanvasComfyNodePort: LazyComponent<typeof import("../app/components/vue-canvas/ComfyNodePort.vue")['default']>
export const LazyVueCanvasComfyNodeWidget: LazyComponent<typeof import("../app/components/vue-canvas/ComfyNodeWidget.vue")['default']>
export const LazyVueCanvasComfyNoteNode: LazyComponent<typeof import("../app/components/vue-canvas/ComfyNoteNode.vue")['default']>
export const LazyVueCanvasCompositorModal: LazyComponent<typeof import("../app/components/vue-canvas/CompositorModal.vue")['default']>
export const LazyVueCanvasCrossfadeModal: LazyComponent<typeof import("../app/components/vue-canvas/CrossfadeModal.vue")['default']>
export const LazyVueCanvasGeneratorsPanel: LazyComponent<typeof import("../app/components/vue-canvas/GeneratorsPanel.vue")['default']>
export const LazyVueCanvasLoRALibraryPanel: LazyComponent<typeof import("../app/components/vue-canvas/LoRALibraryPanel.vue")['default']>
export const LazyVueCanvasNodesCategoryFolder: LazyComponent<typeof import("../app/components/vue-canvas/NodesCategoryFolder.vue")['default']>
export const LazyVueCanvasNodesSidebar: LazyComponent<typeof import("../app/components/vue-canvas/NodesSidebar.vue")['default']>
export const LazyVueCanvasSmartLayoutEditorModal: LazyComponent<typeof import("../app/components/vue-canvas/SmartLayoutEditorModal.vue")['default']>
export const LazyVueCanvasSubgraphBreadcrumb: LazyComponent<typeof import("../app/components/vue-canvas/SubgraphBreadcrumb.vue")['default']>
export const LazyVueCanvasSubgraphIONode: LazyComponent<typeof import("../app/components/vue-canvas/SubgraphIONode.vue")['default']>
export const LazyVueCanvasTimelineModal: LazyComponent<typeof import("../app/components/vue-canvas/TimelineModal.vue")['default']>
export const LazyVueCanvasTimelineNodePreview: LazyComponent<typeof import("../app/components/vue-canvas/TimelineNodePreview.vue")['default']>
export const LazyVueCanvasToolboxPanel: LazyComponent<typeof import("../app/components/vue-canvas/ToolboxPanel.vue")['default']>
export const LazyVueCanvasVueNodeCanvas: LazyComponent<typeof import("../app/components/vue-canvas/VueNodeCanvas.vue")['default']>
export const LazyVueCanvasWorkflowOverview: LazyComponent<typeof import("../app/components/vue-canvas/WorkflowOverview.vue")['default']>
export const LazyVueCanvasWidgetsWidgetCombo: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetCombo.vue")['default']>
export const LazyVueCanvasWidgetsWidgetGradientSlider: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetGradientSlider.vue")['default']>
export const LazyVueCanvasWidgetsWidgetNumber: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetNumber.vue")['default']>
export const LazyVueCanvasWidgetsWidgetSeed: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetSeed.vue")['default']>
export const LazyVueCanvasWidgetsWidgetText: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetText.vue")['default']>
export const LazyVueCanvasWidgetsWidgetToggle: LazyComponent<typeof import("../app/components/vue-canvas/widgets/WidgetToggle.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
