
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  UiAvatar: typeof import("../../app/components/ui/avatar/Avatar.vue")['default']
  UiAvatarFallback: typeof import("../../app/components/ui/avatar/AvatarFallback.vue")['default']
  UiAvatarImage: typeof import("../../app/components/ui/avatar/AvatarImage.vue")['default']
  UiBadge: typeof import("../../app/components/ui/badge/Badge.vue")['default']
  UiButton: typeof import("../../app/components/ui/button/Button.vue")['default']
  UiInput: typeof import("../../app/components/ui/input/Input.vue")['default']
  UiSelect: typeof import("../../app/components/ui/select/Select.vue")['default']
  UiSelectContent: typeof import("../../app/components/ui/select/SelectContent.vue")['default']
  UiSelectGroup: typeof import("../../app/components/ui/select/SelectGroup.vue")['default']
  UiSelectItem: typeof import("../../app/components/ui/select/SelectItem.vue")['default']
  UiSelectLabel: typeof import("../../app/components/ui/select/SelectLabel.vue")['default']
  UiSelectSeparator: typeof import("../../app/components/ui/select/SelectSeparator.vue")['default']
  UiSelectTrigger: typeof import("../../app/components/ui/select/SelectTrigger.vue")['default']
  UiSelectValue: typeof import("../../app/components/ui/select/SelectValue.vue")['default']
  UiSeparator: typeof import("../../app/components/ui/separator/Separator.vue")['default']
  UiSheet: typeof import("../../app/components/ui/sheet/Sheet.vue")['default']
  UiSheetClose: typeof import("../../app/components/ui/sheet/SheetClose.vue")['default']
  UiSheetContent: typeof import("../../app/components/ui/sheet/SheetContent.vue")['default']
  UiSheetDescription: typeof import("../../app/components/ui/sheet/SheetDescription.vue")['default']
  UiSheetFooter: typeof import("../../app/components/ui/sheet/SheetFooter.vue")['default']
  UiSheetHeader: typeof import("../../app/components/ui/sheet/SheetHeader.vue")['default']
  UiSheetOverlay: typeof import("../../app/components/ui/sheet/SheetOverlay.vue")['default']
  UiSheetTitle: typeof import("../../app/components/ui/sheet/SheetTitle.vue")['default']
  UiSheetTrigger: typeof import("../../app/components/ui/sheet/SheetTrigger.vue")['default']
  UiSidebar: typeof import("../../app/components/ui/sidebar/Sidebar.vue")['default']
  UiSidebarContent: typeof import("../../app/components/ui/sidebar/SidebarContent.vue")['default']
  UiSidebarFooter: typeof import("../../app/components/ui/sidebar/SidebarFooter.vue")['default']
  UiSidebarGroup: typeof import("../../app/components/ui/sidebar/SidebarGroup.vue")['default']
  UiSidebarGroupAction: typeof import("../../app/components/ui/sidebar/SidebarGroupAction.vue")['default']
  UiSidebarGroupContent: typeof import("../../app/components/ui/sidebar/SidebarGroupContent.vue")['default']
  UiSidebarGroupLabel: typeof import("../../app/components/ui/sidebar/SidebarGroupLabel.vue")['default']
  UiSidebarHeader: typeof import("../../app/components/ui/sidebar/SidebarHeader.vue")['default']
  UiSidebarInput: typeof import("../../app/components/ui/sidebar/SidebarInput.vue")['default']
  UiSidebarInset: typeof import("../../app/components/ui/sidebar/SidebarInset.vue")['default']
  UiSidebarMenu: typeof import("../../app/components/ui/sidebar/SidebarMenu.vue")['default']
  UiSidebarMenuAction: typeof import("../../app/components/ui/sidebar/SidebarMenuAction.vue")['default']
  UiSidebarMenuBadge: typeof import("../../app/components/ui/sidebar/SidebarMenuBadge.vue")['default']
  UiSidebarMenuButton: typeof import("../../app/components/ui/sidebar/SidebarMenuButton.vue")['default']
  UiSidebarMenuButtonChild: typeof import("../../app/components/ui/sidebar/SidebarMenuButtonChild.vue")['default']
  UiSidebarMenuItem: typeof import("../../app/components/ui/sidebar/SidebarMenuItem.vue")['default']
  UiSidebarMenuSkeleton: typeof import("../../app/components/ui/sidebar/SidebarMenuSkeleton.vue")['default']
  UiSidebarMenuSub: typeof import("../../app/components/ui/sidebar/SidebarMenuSub.vue")['default']
  UiSidebarMenuSubButton: typeof import("../../app/components/ui/sidebar/SidebarMenuSubButton.vue")['default']
  UiSidebarMenuSubItem: typeof import("../../app/components/ui/sidebar/SidebarMenuSubItem.vue")['default']
  UiSidebarProvider: typeof import("../../app/components/ui/sidebar/SidebarProvider.vue")['default']
  UiSidebarRail: typeof import("../../app/components/ui/sidebar/SidebarRail.vue")['default']
  UiSidebarSeparator: typeof import("../../app/components/ui/sidebar/SidebarSeparator.vue")['default']
  UiSidebarTrigger: typeof import("../../app/components/ui/sidebar/SidebarTrigger.vue")['default']
  UiSonner: typeof import("../../app/components/ui/sonner/Sonner.vue")['default']
  UiTextarea: typeof import("../../app/components/ui/textarea/Textarea.vue")['default']
  UiTooltip: typeof import("../../app/components/ui/tooltip/Tooltip.vue")['default']
  UiTooltipContent: typeof import("../../app/components/ui/tooltip/TooltipContent.vue")['default']
  UiTooltipProvider: typeof import("../../app/components/ui/tooltip/TooltipProvider.vue")['default']
  UiTooltipTrigger: typeof import("../../app/components/ui/tooltip/TooltipTrigger.vue")['default']
  AppSidebar: typeof import("../../app/components/AppSidebar.vue")['default']
  AssetBundleOverlay: typeof import("../../app/components/AssetBundleOverlay.vue")['default']
  AssetDetailOverlay: typeof import("../../app/components/AssetDetailOverlay.vue")['default']
  AssetsHistory: typeof import("../../app/components/AssetsHistory.vue")['default']
  ExplainOverlay: typeof import("../../app/components/ExplainOverlay.vue")['default']
  ExplainPanel: typeof import("../../app/components/ExplainPanel.vue")['default']
  LoraTrainerSurface: typeof import("../../app/components/LoraTrainerSurface.vue")['default']
  NodeSearchDialog: typeof import("../../app/components/NodeSearchDialog.vue")['default']
  SettingsModal: typeof import("../../app/components/SettingsModal.vue")['default']
  UserPopup: typeof import("../../app/components/UserPopup.vue")['default']
  AppsAppFileSlot: typeof import("../../app/components/apps/AppFileSlot.vue")['default']
  AppsAutoSubtitleApp: typeof import("../../app/components/apps/AutoSubtitleApp.vue")['default']
  AppsFaceSwapApp: typeof import("../../app/components/apps/FaceSwapApp.vue")['default']
  AppsKaraokeMakerApp: typeof import("../../app/components/apps/KaraokeMakerApp.vue")['default']
  TemplatesEditorCanvas: typeof import("../../app/components/templates/EditorCanvas.vue")['default']
  TemplatesEditorShell: typeof import("../../app/components/templates/EditorShell.vue")['default']
  TemplatesLayersPanel: typeof import("../../app/components/templates/LayersPanel.vue")['default']
  TemplatesPropertyPanel: typeof import("../../app/components/templates/PropertyPanel.vue")['default']
  VueCanvasAnimatedDotGrid: typeof import("../../app/components/vue-canvas/AnimatedDotGrid.vue")['default']
  VueCanvasAsciiPanel: typeof import("../../app/components/vue-canvas/AsciiPanel.vue")['default']
  VueCanvasComfyEdge: typeof import("../../app/components/vue-canvas/ComfyEdge.vue")['default']
  VueCanvasComfyGateNode: typeof import("../../app/components/vue-canvas/ComfyGateNode.vue")['default']
  VueCanvasComfyNode: typeof import("../../app/components/vue-canvas/ComfyNode.vue")['default']
  VueCanvasComfyNodePort: typeof import("../../app/components/vue-canvas/ComfyNodePort.vue")['default']
  VueCanvasComfyNodeWidget: typeof import("../../app/components/vue-canvas/ComfyNodeWidget.vue")['default']
  VueCanvasComfyNoteNode: typeof import("../../app/components/vue-canvas/ComfyNoteNode.vue")['default']
  VueCanvasCompositorModal: typeof import("../../app/components/vue-canvas/CompositorModal.vue")['default']
  VueCanvasCrossfadeModal: typeof import("../../app/components/vue-canvas/CrossfadeModal.vue")['default']
  VueCanvasGeneratorsPanel: typeof import("../../app/components/vue-canvas/GeneratorsPanel.vue")['default']
  VueCanvasLoRALibraryPanel: typeof import("../../app/components/vue-canvas/LoRALibraryPanel.vue")['default']
  VueCanvasNodesCategoryFolder: typeof import("../../app/components/vue-canvas/NodesCategoryFolder.vue")['default']
  VueCanvasNodesSidebar: typeof import("../../app/components/vue-canvas/NodesSidebar.vue")['default']
  VueCanvasSmartLayoutEditorModal: typeof import("../../app/components/vue-canvas/SmartLayoutEditorModal.vue")['default']
  VueCanvasSubgraphBreadcrumb: typeof import("../../app/components/vue-canvas/SubgraphBreadcrumb.vue")['default']
  VueCanvasSubgraphIONode: typeof import("../../app/components/vue-canvas/SubgraphIONode.vue")['default']
  VueCanvasTimelineModal: typeof import("../../app/components/vue-canvas/TimelineModal.vue")['default']
  VueCanvasTimelineNodePreview: typeof import("../../app/components/vue-canvas/TimelineNodePreview.vue")['default']
  VueCanvasToolboxPanel: typeof import("../../app/components/vue-canvas/ToolboxPanel.vue")['default']
  VueCanvasVueNodeCanvas: typeof import("../../app/components/vue-canvas/VueNodeCanvas.vue")['default']
  VueCanvasWorkflowOverview: typeof import("../../app/components/vue-canvas/WorkflowOverview.vue")['default']
  VueCanvasWidgetsWidgetCombo: typeof import("../../app/components/vue-canvas/widgets/WidgetCombo.vue")['default']
  VueCanvasWidgetsWidgetGradientSlider: typeof import("../../app/components/vue-canvas/widgets/WidgetGradientSlider.vue")['default']
  VueCanvasWidgetsWidgetNumber: typeof import("../../app/components/vue-canvas/widgets/WidgetNumber.vue")['default']
  VueCanvasWidgetsWidgetSeed: typeof import("../../app/components/vue-canvas/widgets/WidgetSeed.vue")['default']
  VueCanvasWidgetsWidgetText: typeof import("../../app/components/vue-canvas/widgets/WidgetText.vue")['default']
  VueCanvasWidgetsWidgetToggle: typeof import("../../app/components/vue-canvas/widgets/WidgetToggle.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  ColorScheme: typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']
  NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyUiAvatar: LazyComponent<typeof import("../../app/components/ui/avatar/Avatar.vue")['default']>
  LazyUiAvatarFallback: LazyComponent<typeof import("../../app/components/ui/avatar/AvatarFallback.vue")['default']>
  LazyUiAvatarImage: LazyComponent<typeof import("../../app/components/ui/avatar/AvatarImage.vue")['default']>
  LazyUiBadge: LazyComponent<typeof import("../../app/components/ui/badge/Badge.vue")['default']>
  LazyUiButton: LazyComponent<typeof import("../../app/components/ui/button/Button.vue")['default']>
  LazyUiInput: LazyComponent<typeof import("../../app/components/ui/input/Input.vue")['default']>
  LazyUiSelect: LazyComponent<typeof import("../../app/components/ui/select/Select.vue")['default']>
  LazyUiSelectContent: LazyComponent<typeof import("../../app/components/ui/select/SelectContent.vue")['default']>
  LazyUiSelectGroup: LazyComponent<typeof import("../../app/components/ui/select/SelectGroup.vue")['default']>
  LazyUiSelectItem: LazyComponent<typeof import("../../app/components/ui/select/SelectItem.vue")['default']>
  LazyUiSelectLabel: LazyComponent<typeof import("../../app/components/ui/select/SelectLabel.vue")['default']>
  LazyUiSelectSeparator: LazyComponent<typeof import("../../app/components/ui/select/SelectSeparator.vue")['default']>
  LazyUiSelectTrigger: LazyComponent<typeof import("../../app/components/ui/select/SelectTrigger.vue")['default']>
  LazyUiSelectValue: LazyComponent<typeof import("../../app/components/ui/select/SelectValue.vue")['default']>
  LazyUiSeparator: LazyComponent<typeof import("../../app/components/ui/separator/Separator.vue")['default']>
  LazyUiSheet: LazyComponent<typeof import("../../app/components/ui/sheet/Sheet.vue")['default']>
  LazyUiSheetClose: LazyComponent<typeof import("../../app/components/ui/sheet/SheetClose.vue")['default']>
  LazyUiSheetContent: LazyComponent<typeof import("../../app/components/ui/sheet/SheetContent.vue")['default']>
  LazyUiSheetDescription: LazyComponent<typeof import("../../app/components/ui/sheet/SheetDescription.vue")['default']>
  LazyUiSheetFooter: LazyComponent<typeof import("../../app/components/ui/sheet/SheetFooter.vue")['default']>
  LazyUiSheetHeader: LazyComponent<typeof import("../../app/components/ui/sheet/SheetHeader.vue")['default']>
  LazyUiSheetOverlay: LazyComponent<typeof import("../../app/components/ui/sheet/SheetOverlay.vue")['default']>
  LazyUiSheetTitle: LazyComponent<typeof import("../../app/components/ui/sheet/SheetTitle.vue")['default']>
  LazyUiSheetTrigger: LazyComponent<typeof import("../../app/components/ui/sheet/SheetTrigger.vue")['default']>
  LazyUiSidebar: LazyComponent<typeof import("../../app/components/ui/sidebar/Sidebar.vue")['default']>
  LazyUiSidebarContent: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarContent.vue")['default']>
  LazyUiSidebarFooter: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarFooter.vue")['default']>
  LazyUiSidebarGroup: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarGroup.vue")['default']>
  LazyUiSidebarGroupAction: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarGroupAction.vue")['default']>
  LazyUiSidebarGroupContent: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarGroupContent.vue")['default']>
  LazyUiSidebarGroupLabel: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarGroupLabel.vue")['default']>
  LazyUiSidebarHeader: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarHeader.vue")['default']>
  LazyUiSidebarInput: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarInput.vue")['default']>
  LazyUiSidebarInset: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarInset.vue")['default']>
  LazyUiSidebarMenu: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenu.vue")['default']>
  LazyUiSidebarMenuAction: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuAction.vue")['default']>
  LazyUiSidebarMenuBadge: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuBadge.vue")['default']>
  LazyUiSidebarMenuButton: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuButton.vue")['default']>
  LazyUiSidebarMenuButtonChild: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuButtonChild.vue")['default']>
  LazyUiSidebarMenuItem: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuItem.vue")['default']>
  LazyUiSidebarMenuSkeleton: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuSkeleton.vue")['default']>
  LazyUiSidebarMenuSub: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuSub.vue")['default']>
  LazyUiSidebarMenuSubButton: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuSubButton.vue")['default']>
  LazyUiSidebarMenuSubItem: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarMenuSubItem.vue")['default']>
  LazyUiSidebarProvider: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarProvider.vue")['default']>
  LazyUiSidebarRail: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarRail.vue")['default']>
  LazyUiSidebarSeparator: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarSeparator.vue")['default']>
  LazyUiSidebarTrigger: LazyComponent<typeof import("../../app/components/ui/sidebar/SidebarTrigger.vue")['default']>
  LazyUiSonner: LazyComponent<typeof import("../../app/components/ui/sonner/Sonner.vue")['default']>
  LazyUiTextarea: LazyComponent<typeof import("../../app/components/ui/textarea/Textarea.vue")['default']>
  LazyUiTooltip: LazyComponent<typeof import("../../app/components/ui/tooltip/Tooltip.vue")['default']>
  LazyUiTooltipContent: LazyComponent<typeof import("../../app/components/ui/tooltip/TooltipContent.vue")['default']>
  LazyUiTooltipProvider: LazyComponent<typeof import("../../app/components/ui/tooltip/TooltipProvider.vue")['default']>
  LazyUiTooltipTrigger: LazyComponent<typeof import("../../app/components/ui/tooltip/TooltipTrigger.vue")['default']>
  LazyAppSidebar: LazyComponent<typeof import("../../app/components/AppSidebar.vue")['default']>
  LazyAssetBundleOverlay: LazyComponent<typeof import("../../app/components/AssetBundleOverlay.vue")['default']>
  LazyAssetDetailOverlay: LazyComponent<typeof import("../../app/components/AssetDetailOverlay.vue")['default']>
  LazyAssetsHistory: LazyComponent<typeof import("../../app/components/AssetsHistory.vue")['default']>
  LazyExplainOverlay: LazyComponent<typeof import("../../app/components/ExplainOverlay.vue")['default']>
  LazyExplainPanel: LazyComponent<typeof import("../../app/components/ExplainPanel.vue")['default']>
  LazyLoraTrainerSurface: LazyComponent<typeof import("../../app/components/LoraTrainerSurface.vue")['default']>
  LazyNodeSearchDialog: LazyComponent<typeof import("../../app/components/NodeSearchDialog.vue")['default']>
  LazySettingsModal: LazyComponent<typeof import("../../app/components/SettingsModal.vue")['default']>
  LazyUserPopup: LazyComponent<typeof import("../../app/components/UserPopup.vue")['default']>
  LazyAppsAppFileSlot: LazyComponent<typeof import("../../app/components/apps/AppFileSlot.vue")['default']>
  LazyAppsAutoSubtitleApp: LazyComponent<typeof import("../../app/components/apps/AutoSubtitleApp.vue")['default']>
  LazyAppsFaceSwapApp: LazyComponent<typeof import("../../app/components/apps/FaceSwapApp.vue")['default']>
  LazyAppsKaraokeMakerApp: LazyComponent<typeof import("../../app/components/apps/KaraokeMakerApp.vue")['default']>
  LazyTemplatesEditorCanvas: LazyComponent<typeof import("../../app/components/templates/EditorCanvas.vue")['default']>
  LazyTemplatesEditorShell: LazyComponent<typeof import("../../app/components/templates/EditorShell.vue")['default']>
  LazyTemplatesLayersPanel: LazyComponent<typeof import("../../app/components/templates/LayersPanel.vue")['default']>
  LazyTemplatesPropertyPanel: LazyComponent<typeof import("../../app/components/templates/PropertyPanel.vue")['default']>
  LazyVueCanvasAnimatedDotGrid: LazyComponent<typeof import("../../app/components/vue-canvas/AnimatedDotGrid.vue")['default']>
  LazyVueCanvasAsciiPanel: LazyComponent<typeof import("../../app/components/vue-canvas/AsciiPanel.vue")['default']>
  LazyVueCanvasComfyEdge: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyEdge.vue")['default']>
  LazyVueCanvasComfyGateNode: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyGateNode.vue")['default']>
  LazyVueCanvasComfyNode: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyNode.vue")['default']>
  LazyVueCanvasComfyNodePort: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyNodePort.vue")['default']>
  LazyVueCanvasComfyNodeWidget: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyNodeWidget.vue")['default']>
  LazyVueCanvasComfyNoteNode: LazyComponent<typeof import("../../app/components/vue-canvas/ComfyNoteNode.vue")['default']>
  LazyVueCanvasCompositorModal: LazyComponent<typeof import("../../app/components/vue-canvas/CompositorModal.vue")['default']>
  LazyVueCanvasCrossfadeModal: LazyComponent<typeof import("../../app/components/vue-canvas/CrossfadeModal.vue")['default']>
  LazyVueCanvasGeneratorsPanel: LazyComponent<typeof import("../../app/components/vue-canvas/GeneratorsPanel.vue")['default']>
  LazyVueCanvasLoRALibraryPanel: LazyComponent<typeof import("../../app/components/vue-canvas/LoRALibraryPanel.vue")['default']>
  LazyVueCanvasNodesCategoryFolder: LazyComponent<typeof import("../../app/components/vue-canvas/NodesCategoryFolder.vue")['default']>
  LazyVueCanvasNodesSidebar: LazyComponent<typeof import("../../app/components/vue-canvas/NodesSidebar.vue")['default']>
  LazyVueCanvasSmartLayoutEditorModal: LazyComponent<typeof import("../../app/components/vue-canvas/SmartLayoutEditorModal.vue")['default']>
  LazyVueCanvasSubgraphBreadcrumb: LazyComponent<typeof import("../../app/components/vue-canvas/SubgraphBreadcrumb.vue")['default']>
  LazyVueCanvasSubgraphIONode: LazyComponent<typeof import("../../app/components/vue-canvas/SubgraphIONode.vue")['default']>
  LazyVueCanvasTimelineModal: LazyComponent<typeof import("../../app/components/vue-canvas/TimelineModal.vue")['default']>
  LazyVueCanvasTimelineNodePreview: LazyComponent<typeof import("../../app/components/vue-canvas/TimelineNodePreview.vue")['default']>
  LazyVueCanvasToolboxPanel: LazyComponent<typeof import("../../app/components/vue-canvas/ToolboxPanel.vue")['default']>
  LazyVueCanvasVueNodeCanvas: LazyComponent<typeof import("../../app/components/vue-canvas/VueNodeCanvas.vue")['default']>
  LazyVueCanvasWorkflowOverview: LazyComponent<typeof import("../../app/components/vue-canvas/WorkflowOverview.vue")['default']>
  LazyVueCanvasWidgetsWidgetCombo: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetCombo.vue")['default']>
  LazyVueCanvasWidgetsWidgetGradientSlider: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetGradientSlider.vue")['default']>
  LazyVueCanvasWidgetsWidgetNumber: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetNumber.vue")['default']>
  LazyVueCanvasWidgetsWidgetSeed: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetSeed.vue")['default']>
  LazyVueCanvasWidgetsWidgetText: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetText.vue")['default']>
  LazyVueCanvasWidgetsWidgetToggle: LazyComponent<typeof import("../../app/components/vue-canvas/widgets/WidgetToggle.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.0_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@parc_fc038336139629208295ec9d50518fbc/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
