// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cloud-train/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cloud-train/start.post').default>>>>
    }
    '/api/cloud-train/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cloud-train/status.get').default>>>>
    }
    '/api/cloud-train/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cloud-train/upload.post').default>>>>
    }
    '/api/explain': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explain.post').default>>>>
    }
    '/api/lora-preview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lora-preview.get').default>>>>
    }
    '/api/render-template': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/render-template.post').default>>>>
    }
    '/api/templates/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/[id].put').default>>>>
    }
    '/api/templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/index.get').default>>>>
    }
    '/history/:promptId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/history/[promptId].get').default>>>>
    }
    '/history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/history/index.get').default>>>>
    }
    '/view': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/view.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_db0@0.3.4_ioredis@5.10.0_magicast@0.5.2_nux_de30a4775c400e20e49bcd2c4abc061c/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}